name: 'Laravel Deploy X'

description: 'Deploy Laravel Application to Server via SSH by RSync'
author: 'MJA'
branding:
    icon: 'send'
    color: 'green'

inputs:
    user: 
        description: 'Deploy user'
        required: true
    host: 
        description: 'Deploy host'
        required: true
    port: 
        description: 'Deploy port'
        required: false
    path: 
        description: 'Path on server'
        required: true
    sourcePath:
        description: 'Path source in project if not the hole project should be deployd (i.e. vue-projects)'
        required: true
        default: '.'
    owner: 
        description: 'Deploy owner'
        required: true
    useArtisan: 
        description: 'Disables the artisan migrate and cache-cleaing commands if set to "0"'
        required: false
        default: '1'
    commands: 
        description: 'Command to run after default artisan commands'
        required: false
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        -   ${{ inputs.user }}
        -   ${{ inputs.host }}
        -   ${{ inputs.port }}
        -   ${{ inputs.path }}
        -   ${{ inputs.owner }}
        -   ${{ inputs.useArtisan }}
        -   ${{ inputs.commands }}
